pool:
  vmImage: ubuntu-22.04

trigger:
  - master
  
schedules:
  - cron: '30 1 * * 6'
    displayName: Weekly build
    branches:
      include:
        - master

parameters:
  - name : jdk version
    displayName: java version
    type: string
    default: 1.8
    values:
      - '1.8'
      - '1.17'
      - '1.14'                
jobs:
  - job: build
    displayName: 'building using maven' 
    steps:
      - task: Maven@4
        inputs:
          mavenPOMFile: 'pom.xml'
          goals: clean package
          publishjunitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: "${{ parameters.jdkversion }}"

                 